INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (321, 66, 6);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (321, 77, 7);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (321, 88, 8);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (321, 87, 5);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (321, 86, 4);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (321, 85, 3);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (322, 85, 3);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (322, 85, 3);
INSERT INTO ORDER_LINE (order_id, goods_id, order_line_count) VALUES (322, 85, 3);